local:
  host: http://localhost:3003
  handle: solitary-sands-6544
  email: abc@gmail.com
  api_key: 8bd9b13ffca6fe23002654b0403e446c844671a4
staging:
  host: station.locomotive.works
  handle: my-site-staging
  email: john@doe.net
  api_key: 373e4330e47d30456221caa4e6b174428b9a1de

production:
  host: http://www.productdatalake.com
  handle: pdl
  email: abc111@gmail.com
  api_key: 263e7529ae54c9f158f02f38335e23e5df593e98
